<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
	<AssemblyVersion>26.8.17.1701</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.4" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\PrismDemo.Core\PrismDemo.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="a.config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <Target Name="CopyToModules" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)PrismDemo.A.dll" DestinationFolder="$(MSBuildProjectDirectory)\..\PrismDemo.APP\bin\$(Configuration)\Modules\" />
    <Copy SourceFiles="$(OutputPath)a.config.json" DestinationFolder="$(MSBuildProjectDirectory)\..\PrismDemo.APP\bin\$(Configuration)\Modules\" />
  </Target>
</Project>